// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Icon: typeof import('~icons/ic/on')['default']
    Introduction: typeof import('./components/Introduction.vue')['default']
    MdiCheck: typeof import('~icons/mdi/check')['default']
    MdiEmailOutline: typeof import('~icons/mdi/email-outline')['default']
    MdiGithub: typeof import('~icons/mdi/github')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
