# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the workflow will run
on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with: 
          version: 6.20.4

      - name: Setup Node.js ${{ secrets.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build Packages
        run: pnpm run build
        
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_PRIVATE_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: "./dist"
          REMOTE_HOST: ${{ secrets.REMOTE_SERVER }}
          REMOTE_USER: "root"
          TARGET: ${{ secrets.TARGET_FOLDER }}
